### ISSUE TITLE
So I fixed a ton

### ISSUE THREAD

**Issue by katz0018** [katz0018/volunteer-form#3]
I am very close I think, but I markbot is telling me there are duplicate yes and no, what does this mean? and also says the naming conventions on GitHub are wrong for the file

**Comment by katz0018** [comment]
@mpelletiervaillant

**Comment by mpelletiervaillant-zz** [comment]
For the wrapper, don't put in on the section because then it makes the header small. Make another section surrounding the form only and put wrapper there. 

Fort the yes/no, you can't have the same name for the label and id. So name each one differently (ex. license-yes, license-no, truck-yes. truck-no...)

And it looks like your index is called (index) and not index.html

Hope this helps!
